### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by freerider7777**
I was following the example but this lines did not work (Undefined). Without "var" keyword everything works, 42 is returned ok :)

### CODE REVIEW

**Comment by freerider7777** [comment]
var keyword seems not needed

**Comment by patrickmn** [comment]
var is clearer if for no other reason than it indicates the variables weren't previously declared somewhere else, i.e. you are not giving some magic variables their values, but just declaring new ones.

**Comment by freerider7777** [comment]
Ok, but it did not work with "var" - there was an error
"I was following the example but this lines did not work"
screenshot:
[https://cloud.mail.ru/public/KdGo/dwD7zz5kB](https://cloud.mail.ru/public/KdGo/dwD7zz5kB)

**Comment by patrickmn** [comment]
That's working.

Try:

    var address = "foo"
    address

You should see "foo".

You see "undefined" because assignment doesn't yield a return value.

**Pull request closed without merging**
