### PR TITLE
examples: add full syncmode flag

### PR DESCRIPTION
**Pull request by markya0616**

### CODE REVIEW

**Comment by yutelin** [comment]
Currently starting a new network would need the initial validators to run with `--syncmode full` option.

**Comment by tylobban** [comment]
@yutelin can you please describe the impact of having to run in this mode and also why this is needed? Can an initial validator later turn this off?

**Comment by markya0616** [comment]
The sync mode affects only if there are some existing blocks, so there is no impact if we only run the initial validators in `full` mode in a new network. 

We use fetcher to insert block. If we don't set to `full` mode, the fetcher cannot insert the first block. Please refer below code in `eth/handler.go`.

```
inserter := func(blocks types.Blocks) (int, error) {
		// If fast sync is running, deny importing weird blocks
		if atomic.LoadUint32(&manager.fastSync) == 1 {
			log.Warn("Discarded bad propagated block", "number", blocks[0].Number(), "hash", blocks[0].Hash())
			return 0, nil
		}
		atomic.StoreUint32(&manager.acceptTxs, 1) // Mark initial sync done on any fetcher import
		return manager.blockchain.InsertChain(blocks)
	}
```

For the later joined validators, we don't need to use `full` mode. The following validators can get blocks by downloader. After the first sync from peer, they will automatically switch to `full` mode. We don't need to turn it off.

**Comment by patrickmn** [comment]
This should probably be documented as well.

For the record, the default sync mode changed from `full` to `fast` in 1.6.

**Review by patrickmn — APPROVED** [review]

**Comment by patrickmn** [comment]
@markya0616, could you kindly execute the CLA (https://github.com/jpmorganchase/cla) as well?

**Comment by markya0616** [comment]
@patrickmn done. I've sent a cla mail to quorum_cla@jpmorgan.com .

**Comment by patrickmn** [comment]
Thank you. Received and merged :)

**Comment by Kl4rity** [comment]
Hi there, I am working on setting up quorum nodes and, unfortunately, they seem to neither recognise the --syncmode 'full' nor the --mine or --minerthreads 1 arguments. It does accept all other arguments such as --datadir, --rpc etc...

Everything is based on the https://github.com/jpmorganchase/quorum.git repo (geth version etc.)

The full command I am trying to execute is the 
`geth --datadir /qdata/dd --mine --minerthreads 1 --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --nodiscover --unlock 0 --password /qdata/passwords.txt`

The log message I then get is:
"flag provided but not defined: -mine"

This only depends on which command of these 3 **--mine --minerthreads 1 --syncmode full** is first in the above command.

(Constellation Node starts fine.)

Any idea why this happens? I've been playing around with this for some time now and can't get it to recognise the flags. Thank you!

**Pull request merged**
