### PR TITLE
support PRIVATE_CONFIG=ignore 

### PR DESCRIPTION
**Pull request by zouguangxian**
support PRIVATE_CONFIG=ignore to start a Quorum node without its associated privacy transaction manager
fix read error for disallowed-nodes.json file

### CODE REVIEW

**Review by trung — CHANGES_REQUESTED** [review]
Please also update README, step 3 under "Running with Docker" section to illustrate the way to start network without Private Transaction Manager

**Comment by prd-fox** [comment]
Should we also update the non-docker scripts?

**Comment by zouguangxian** [comment]
> Please also update README, step 3 under "Running with Docker" section to illustrate the way to start network without Private Transaction Manager

I have updated README. Please review it.

**Review by trung — APPROVED** [review]
Lgtm

**Review by fixanoid — APPROVED** [review]

**Comment by fixanoid** [comment]
Thank you for the contribution!

**Pull request merged**
